FROM node:20 AS build
WORKDIR /app
ARG VITE_API_BASE_URL
ARG VITE_API_RESULT_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_RESULT_URL=$VITE_API_RESULT_URL
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]